name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: akhileshns/heroku-deploy@v3.7.8
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "desolate-basin-11702"
          heroku_email: "korostovska@gmail.com"
          healthcheck: "https://desolate-basin-11702.herokuapp.com/version"
          checkstring: "This is a new version, code has been updated yaay 🥳"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - uses: 8398a7/action-slack@v3.8.1
        with:
          status: custom
          channel: '#general'
          icon_emoji: ':octocat:'
          fields: all
          custom_payload: |
            {
              username: 'action-slack',
              attachments: [{
                "author_name": "8398a7@action-slack"
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `workflow ${process.env.AS_WORKFLOW}\n job ${process.env.AS_JOB}\n eventName ${process.env.AS_EVENT_NAME}\n commit message ${process.env.}\n  commit (${process.env.AS_COMMIT})\n  repo ${process.env.AS_REPO}@${process.env.AS_REF}\n author ${process.env.AS_AUTHOR}\n took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
