name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple-deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: akhileshns/heroku-deploy@v3.7.8
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "desolate-basin-11702"
          heroku_email: "korostovska@gmail.com"
          healthcheck: "https://desolate-basin-11702.herokuapp.com/version"
          checkstring: "This is a new version, code has been updated yaay 🥳"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
